name: Go Deployment

on:
  push:
    branches:
      - master  # 触发条件可以根据你的需求进行修改

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'  # 可以根据你的需求指定 Go 版本

      - name: Build
        run: go build -o myapp

      - name: Deploy
        run: |

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 如果需要 SSH 认证，需要设置密钥

